### ISSUE TITLE
Typing invalid value clears date input

### ISSUE THREAD

**Issue by Jen-ni** [OpusCapita/react-datetime#17]
Changing date by typing is complicated, because date input field is cleared (year is autofixed instead), when it becomes invalid. Problem appeared in version 3.0.0.

How to reproduce clearing:
1) Open demo: https://opuscapita.github.io/react-datetime/
2) Edit Date Input sample 04/22/2013 by removing 4. 
Outcome: Date becomes invalid and input field is cleared.
Expected outcome: Date input should become invalid but input value should stay uncleared 0/22/2013

How to reproduce autofixing:
1) Open demo: https://opuscapita.github.io/react-datetime/
2) Edit Date Input sample 04/22/2013 by removing 3. 
Outcome: Date becomes invalid and input value is autofixed 04/22/0201.
Expected outcome: Date input should become invalid and input value should stay unfixed 04/22/201

**Comment by bo-kh** [comment]
Fixed here 162b0b27f2576680782a95d8b39f25ee37f4a930

**Comment by Jen-ni** [comment]
Clearing part is verified OK, but year autofixing is open.

**Comment by bo-kh** [comment]
Put years to the year-list starting from 0000 and you will see the correct year in a picker :) Your picker contains years only from 2008 to 2028

**Comment by Jen-ni** [comment]
Right, this work quite ok. If we use strict mode, then we also loose useful day & month autofixing (if format is DD.MM.YYYY then 4/8/2013 would not be accepted). Therefore I agree that let's leave it like this.
